### ISSUE TITLE
怎么编译啊大佬

### ISSUE THREAD

**Issue by niansir** [heyaug/HttpSo#1]
怎么编译啊大佬

**Comment by heyaug** [comment]
我是用IEDA，可以直接运行或者build

**Comment by niansir** [comment]
您能贴一个命令吗？不太懂这个编译和使用的方法

**Comment by heyaug** [comment]
你可以看看这个https://mp.weixin.qq.com/s/Do4rGrMNFGx5HqFKM9vA1g
我是在这个基础上开发的

**Comment by niansir** [comment]
好的，请问一下 访问次数多了 不会返回数据 请问这个有什么好的解决方法吗？

**Comment by heyaug** [comment]
如果自用可以手动注册一些设备，然后降低频率

**Comment by niansir** [comment]
device_id 通过这个生成的不能用 我可以多弄几个手机 加代理IP的方式 这样可以吗

**Comment by heyaug** [comment]
可以看看这个：https://github.com/virjar/sekiro

**Comment by niansir** [comment]
好的 谢谢
