### ISSUE TITLE
你好，能否发一下10.9.0对应的apk文件

### ISSUE THREAD

**Issue by MushroomLqy** [heyaug/HttpSo#3]

**Comment by MushroomLqy** [comment]
邮箱876904376@qq.com

**Comment by Whusan** [comment]
大哥 我也想要

**Comment by Whusan** [comment]
邮箱2143549151@qq.com

**Comment by wei168hua** [comment]
我没有APP编译环境我也需要：weihua168@live.com

**Comment by HappyTestingc** [comment]
大佬，求10.9.0对应的apk包，邮箱944946217@qq.com

**Comment by Whusan** [comment]
可安装在手机或者雷电模拟器最新版


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "heyaug/HttpSo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 中午11:47
收件人:&nbsp;"heyaug/HttpSo"<HttpSo@noreply.github.com&gt;;
抄送:&nbsp;"鍶唸.哪箇祂"<948268101@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [heyaug/HttpSo] 你好，能否发一下10.9.0对应的apk文件 (#3)





 
Closed #3.
